services:
  ITBMedia\FortnoxBundle\Controller\FortnoxController:
    public: true
    tags: ['controller.service_arguments']

  itbmedia_fortnox.service:
    class: ITBMedia\FortnoxBundle\Service\FortnoxService
    public: true
    arguments:
      $parameterBag: "@parameter_bag"
      $eventDispatcher: "@event_dispatcher"
   
  itbmedia_fortnox.controller:
    class: ITBMedia\FortnoxBundle\Controller\FortnoxController
    public: true
    arguments:
      $parameterBag: "@parameter_bag"
      $eventDispatcher: "@event_dispatcher"
      $session: "@session"
    calls:
      - setContainer: ["@service_container"]
    