services:
  itbmedia_fortnox.callback.controller:
    class: ITBMedia\FortnoxBundle\Controller\CallbackController
    public: true
    arguments: []
    
  itbmedia_fortnox.service:
    class: ITBMedia\FortnoxBundle\Service\FortnoxService
    public: true
    arguments:
      $parameterBag: "@parameter_bag"