services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
  
  ITBMedia\FortnoxBundle\:
    resource: '../../../src/'
    exclude:
      - '../../../DependencyInjection/'
      - '../../../src/Entity/'
      - '../../../src/Kernel.php'

  itbmedia_fortnox.service:
    class: ITBMedia\FortnoxBundle\Service\FortnoxService
    public: true
    arguments:
      $parameterBag: "@parameter_bag"
      $eventDispatcher: "@event_dispatcher"

  itbmedia_fortnox.controller:
    class: ITBMedia\FortnoxBundle\Controller\FortnoxController
    public: true
  