services:
  ITBMedia\FortnoxBundle\Controller\FortnoxController:
    public: true
    autowire: true
    tags: ["controller.service_arguments"]

  itbmedia_fortnox.service:
    class: ITBMedia\FortnoxBundle\Service\FortnoxService
    public: true
    arguments:
      $parameterBag: "@parameter_bag"
      $eventDispatcher: "@event_dispatcher"
      $lockStoreFactory: "@itbmedia_fortnox.lock_store_factory"
      $cacheFactory: "@itbmedia_fortnox.cache_factory"

  itbmedia_fortnox.controller:
    class: ITBMedia\FortnoxBundle\Controller\FortnoxController
    public: true
    autowire: true
    calls:
      - setContainer: ["@service_container"]

  function_provider:
    class: ITBMedia\FortnoxBundle\Providers\ProviderFunctions
    tags: ["jms.expression.function_provider"]

  itbmedia_fortnox.lock_store_factory:
    class: ITBMedia\FortnoxBundle\Factory\LockStoreFactory
    public: true
    arguments:
      $parameterBag: "@parameter_bag"

  itbmedia_fortnox.cache_factory:
    class: ITBMedia\FortnoxBundle\Factory\CacheFactory
    public: true
    arguments:
      $parameterBag: "@parameter_bag"
