services:  
  ITBMedia\FortnoxBundle\EventListener\PropertyEvent:
    tags:
      - { name: kernel.event_listener, event: itbmedia_annotation.access_event }

  itbmedia_fortnox.controller:
    class: ITBMedia\FortnoxBundle\Controller\FortnoxController
    public: true
    arguments: 
      $parameterBag: "@parameter_bag"
      $eventDispatcher: "@event_dispatcher"
      $session: "@session"

  itbmedia_fortnox.service:
    class: ITBMedia\FortnoxBundle\Service\FortnoxService
    public: true
    arguments:
      $parameterBag: "@parameter_bag"
      $eventDispatcher: "@event_dispatcher"
      $tokenStorage: "@security.token_storage"